### ISSUE TITLE
Add support for GraphQL?

### ISSUE THREAD

**Issue by genomics-geek** [chopdgd/cookiecutter-django-reactjs#11]
Currently the template sets up a REST api.  However, GraphQL is a great way to build modern web applications.

What this would involve:

+ Backend: [django graphene](https://docs.graphene-python.org/projects/django/en/latest/) install and setup 
+ Fronted: [React Apollo](https://www.apollographql.com/docs/react/) install and setup

**Comment by Afrowave** [comment]
Yes, it would. I have had a look at Apollo recently as I was in a Javascript only environment. I have not used Django Graphene yet on a project. I should do so soon though.
